const DUMMY_DATA = [
    {
        id: 1,
        testLinkId: "ABCD-123412",
        testPackage: 'This is the name of a test package',
        testClass: 'This is the name of a test class',
        testName: 'This is the name of an individual test it\'s kinda long',
        testPriority: 'High',
        generalWorkflow: 'Authorisation',
        specificWorkflow: 'Login',
        setToIgnore: true,
        comments: 'Test comment',
        partialCoverageOnly: false,
        bugTicket: "BugNum-123456",
        status: [{ user: 'RJB', verdict: 'Ok' }, { user: 'CL', verdict: 'Bug' }]
    },
    {
        id: 2,
        testLinkId: "EFGH-567890",
        testPackage: 'Test Package 2',
        testClass: 'Test Class 2',
        testName: 'Individual Test 2',
        testPriority: 'Medium',
        generalWorkflow: 'Authentication',
        specificWorkflow: 'Registration',
        setToIgnore: false,
        comments: 'Test comment 2',
        partialCoverageOnly: true,
        bugTicket: "BugNum-234567"
    },
    {
        id: 3,
        testLinkId: "IJKL-098765",
        testPackage: 'Test Package 3',
        testClass: 'Test Class 3',
        testName: 'Individual Test 3',
        testPriority: 'Low',
        generalWorkflow: 'Authorisation',
        specificWorkflow: 'Password Reset',
        setToIgnore: false,
        comments: 'Test comment 3',
        partialCoverageOnly: false,
        bugTicket: "BugNum-345678",
        status: [{ user: 'OV', verdict: 'Unsure' }]
    },
    {
        id: 4,
        testLinkId: "MNOP-654321",
        testPackage: 'Test Package 4',
        testClass: 'Test Class 4',
        testName: 'Individual Test 4',
        testPriority: 'Smoke',
        generalWorkflow: 'Authentication',
        specificWorkflow: 'Multi-Factor Authentication',
        setToIgnore: true,
        comments: 'Test comment 4',
        partialCoverageOnly: true,
        bugTicket: "BugNum-456789"
    },
    {
        id: 5,
        testLinkId: "QRST-987654",
        testPackage: 'Test Package 5',
        testClass: 'Test Class 5',
        testName: 'Individual Test 5',
        testPriority: 'Medium',
        generalWorkflow: 'Authorisation',
        specificWorkflow: 'API Access',
        setToIgnore: false,
        comments: 'Test comment 5',
        partialCoverageOnly: false,
        bugTicket: "BugNum-567890"
    },
    {
        id: 6,
        testLinkIdid: "ABCD-123412",
        testPackage: 'This is the name of a test package',
        testClass: 'This is the name of a test class',
        testName: 'This is the name of an individual test it\'s kinda long',
        testPriority: 'High',
        generalWorkflow: 'Authorisation',
        specificWorkflow: 'Login',
        setToIgnore: true,
        comments: 'Test comment',
        partialCoverageOnly: false,
        bugTicket: "BugNum-123456"
    },
    {
        id: 7,
        testLinkId: "EFGH-567890",
        testPackage: 'Test Package 2',
        testClass: 'Test Class 2',
        testName: 'Individual Test 2',
        testPriority: 'Medium',
        generalWorkflow: 'Authentication',
        specificWorkflow: 'Registration',
        setToIgnore: false,
        comments: 'Test comment 2',
        partialCoverageOnly: true,
        bugTicket: "BugNum-234567"
    },
    {
        id: 8,
        testLinkId: "IJKL-098765",
        testPackage: 'Test Package 3',
        testClass: 'Test Class 3',
        testName: 'Individual Test 3',
        testPriority: 'Low',
        generalWorkflow: 'Authorisation',
        specificWorkflow: 'Password Reset',
        setToIgnore: false,
        comments: 'Test comment 3',
        partialCoverageOnly: false,
        bugTicket: "BugNum-345678"
    },
    {
        id: 9,
        testLinkId: "MNOP-654321",
        testPackage: 'Test Package 4',
        testClass: 'Test Class 4',
        testName: 'Individual Test 4',
        testPriority: 'High',
        generalWorkflow: 'Authentication',
        specificWorkflow: 'Multi-Factor Authentication',
        setToIgnore: true,
        comments: 'Test comment 4',
        partialCoverageOnly: true,
        bugTicket: "BugNum-456789"
    },
    {
        id: 10,
        testLinkId: "QRST-987654",
        testPackage: 'Test Package 5',
        testClass: 'Test Class 5',
        testName: 'Individual Test 5',
        testPriority: 'Medium',
        generalWorkflow: 'Authorisation',
        specificWorkflow: 'API Access',
        setToIgnore: false,
        comments: 'Test comment 5',
        partialCoverageOnly: false,
        bugTicket: "BugNum-567890"
    },
    {
        id: 11,
        testLinkIdid: "ABCD-123412",
        testPackage: 'This is the name of a test package',
        testClass: 'This is the name of a test class',
        testName: 'This is the name of an individual test it\'s kinda long',
        testPriority: 'High',
        generalWorkflow: 'Authorisation',
        specificWorkflow: 'Login',
        setToIgnore: true,
        comments: 'Test comment',
        partialCoverageOnly: false,
        bugTicket: "BugNum-123456"
    },
    {
        id: 12,
        testLinkId: "EFGH-567890",
        testPackage: 'Test Package 2',
        testClass: 'Test Class 2',
        testName: 'Individual Test 2',
        testPriority: 'Medium',
        generalWorkflow: 'Authentication',
        specificWorkflow: 'Registration',
        setToIgnore: false,
        comments: 'Test comment 2',
        partialCoverageOnly: true,
        bugTicket: "BugNum-234567"
    },
    {
        id: 13,
        testLinkId: "IJKL-098765",
        testPackage: 'Test Package 3',
        testClass: 'Test Class 3',
        testName: 'Individual Test 3',
        testPriority: 'Low',
        generalWorkflow: 'Authorisation',
        specificWorkflow: 'Password Reset',
        setToIgnore: false,
        comments: 'Test comment 3',
        partialCoverageOnly: false,
        bugTicket: "BugNum-345678"
    },
    {
        id: 14,
        testLinkId: "MNOP-654321",
        testPackage: 'Test Package 4',
        testClass: 'Test Class 4',
        testName: 'Individual Test 4',
        testPriority: 'High',
        generalWorkflow: 'Authentication',
        specificWorkflow: 'Multi-Factor Authentication',
        setToIgnore: true,
        comments: 'Test comment 4',
        partialCoverageOnly: true,
        bugTicket: "BugNum-456789"
    },
    {
        id: 15,
        testLinkId: "QRST-987654",
        testPackage: 'Test Package 5',
        testClass: 'Test Class 5',
        testName: 'Individual Test 5',
        testPriority: 'Medium',
        generalWorkflow: 'Authorisation',
        specificWorkflow: 'API Access',
        setToIgnore: false,
        comments: 'Test comment 5',
        partialCoverageOnly: false,
        bugTicket: "BugNum-567890"
    },
    {
        id: 16,
        testLinkIdid: "ABCD-123412",
        testPackage: 'This is the name of a test package',
        testClass: 'This is the name of a test class',
        testName: 'This is the name of an individual test it\'s kinda long',
        testPriority: 'High',
        generalWorkflow: 'Authorisation',
        specificWorkflow: 'Login',
        setToIgnore: true,
        comments: 'Test comment',
        partialCoverageOnly: false,
        bugTicket: "BugNum-123456"
    },
    {
        id: 17,
        testLinkId: "EFGH-567890",
        testPackage: 'Test Package 2',
        testClass: 'Test Class 2',
        testName: 'Individual Test 2',
        testPriority: 'Medium',
        generalWorkflow: 'Authentication',
        specificWorkflow: 'Registration',
        setToIgnore: false,
        comments: 'Test comment 2',
        partialCoverageOnly: true,
        bugTicket: "BugNum-234567"
    },
    {
        id: 18,
        testLinkId: "IJKL-098765",
        testPackage: 'Test Package 3',
        testClass: 'Test Class 3',
        testName: 'Individual Test 3',
        testPriority: 'Low',
        generalWorkflow: 'Authorisation',
        specificWorkflow: 'Password Reset',
        setToIgnore: false,
        comments: 'Test comment 3',
        partialCoverageOnly: false,
        bugTicket: "BugNum-345678"
    },
    {
        id: 19,
        testLinkId: "MNOP-654321",
        testPackage: 'Test Package 4',
        testClass: 'Test Class 4',
        testName: 'Individual Test 4',
        testPriority: 'High',
        generalWorkflow: 'Authentication',
        specificWorkflow: 'Multi-Factor Authentication',
        setToIgnore: true,
        comments: 'Test comment 4',
        partialCoverageOnly: true,
        bugTicket: "BugNum-456789"
    },
    {
        id: 20,
        testLinkId: "QRST-987654",
        testPackage: 'Test Package 5',
        testClass: 'Test Class 5',
        testName: 'Individual Test 5',
        testPriority: 'Medium',
        generalWorkflow: 'Authorisation',
        specificWorkflow: 'API Access',
        setToIgnore: false,
        comments: 'Test comment 5',
        partialCoverageOnly: false,
        bugTicket: "BugNum-567890"
    },
];

export default DUMMY_DATA;